name:               "SwiiT"
description:        "Stijn Willems"

url:                "https://stekkew.github.io"
author:             "stekkew"
email:              "info@swiit.me"
gravatar_hash:      "4e9d7298c749f46ba4cb31bcae7c17f7"
twitter:            "stekkew"
email:              "info@swiit.me"
github:             "stekkew"
linkedin:           "stijn-willems-6b7b4861"
facebook:           "stekkew"
youtube:            "stekkew"

disqus_shortname:   "stekkew"

background:         "https://stekkew.github.io/resources/wall-175498_1280.jpg"

paginate:           0
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Projects"
    href:           "/projects"
  - name:           "Ink"
    href:           "/ink"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
