name:               "SwiiT"
description:        "Stijn Willems"

url:                "https://stekkew.github.io"
author:             "stekkew"
email:              "info@swiit.me"
gravatar_hash:      "4e9d7298c749f46ba4cb31bcae7c17f7"
twitter:            "stekkew"
email:              "info@swiit.me"
github:             "stekkew"
linkedin:           "stijn-willems-6b7b4861"
facebook:           "stekkew"
youtube:            "stekkew"

disqus_shortname:   "stekkew"

background:         "https://www.google.be/url?sa=i&rct=j&q=&esrc=s&source=imgres&cd=&cad=rja&uact=8&ved=0ahUKEwjdy8-V7ZvRAhWHNFAKHZuEDdIQjRwIBw&url=https%3A%2F%2Fpixabay.com%2Fen%2Fwall-abstract-concrete-gray-white-175498%2F&psig=AFQjCNFMOh_FI9XzKGTmxilvNZWqjglXxg&ust=1483185091624146"

paginate:           0
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Projects"
    href:           "/projects"
  - name:           "Ink"
    href:           "/ink"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
