name:               "SwiiT"
description:        "Stijn Willems"

url:                "http://swiit.me"
author:             "stekkew"
email:              "info@swiit.me"
gravatar_hash:      "4e9d7298c749f46ba4cb31bcae7c17f7"
twitter:            "stekkew"
email:              "info@swiit.me"
github:             "stekkew"
pinterest:          "stijn0928"
linkedin:           "stijn-willems-6b7b4861"
facebook:           "stekkew"

disqus_shortname:   "stekkew"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
